// packages/angular/src/lib/accordion.component.ts
import { Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';

/* ---------- Accordion ---------- */

@Component({
  selector: 'sds-accordion',
  standalone: true,
  imports: [CommonModule],
  host: {
    '[class]': 'hostClasses',
  },
  template: `<ng-content />`,
})
export class SdsAccordionComponent {
  @Input() bordered = false;

  get hostClasses(): string {
    return [
      'sds-accordion',
      this.bordered && 'sds-accordion--bordered',
    ]
      .filter(Boolean)
      .join(' ');
  }
}

/* ---------- Accordion Item ---------- */

@Component({
  selector: 'sds-accordion-item',
  standalone: true,
  imports: [CommonModule],
  host: {
    class: 'sds-accordion-item',
  },
  template: `
    <button
      type="button"
      class="sds-accordion-header"
      [attr.aria-expanded]="expanded"
      (click)="toggle()"
    >
      <span class="sds-accordion-header-text">{{ title }}</span>
      <span class="sds-accordion-icon"></span>
    </button>
    <div *ngIf="expanded" class="sds-accordion-panel">
      <div class="sds-accordion-panel-inner">
        <ng-content />
      </div>
    </div>
  `,
})
export class SdsAccordionItemComponent {
  @Input() title = '';
  @Input() expanded = false;

  toggle(): void {
    this.expanded = !this.expanded;
  }
}

// packages/react/src/components/Accordion/Accordion.tsx
import { forwardRef, useState } from 'react';

/* ---------- Accordion ---------- */

export interface AccordionProps extends React.HTMLAttributes<HTMLDivElement> {
  bordered?: boolean;
}

export const Accordion = forwardRef<HTMLDivElement, AccordionProps>(
  ({ bordered, className, children, ...rest }, ref) => {
    const classes = [
      'sds-accordion',
      bordered && 'sds-accordion--bordered',
      className,
    ]
      .filter(Boolean)
      .join(' ');

    return (
      <div ref={ref} className={classes} {...rest}>
        {children}
      </div>
    );
  },
);

Accordion.displayName = 'Accordion';

/* ---------- AccordionItem ---------- */

export interface AccordionItemProps
  extends React.HTMLAttributes<HTMLDivElement> {
  title: string;
  defaultOpen?: boolean;
}

export const AccordionItem = forwardRef<HTMLDivElement, AccordionItemProps>(
  ({ title, defaultOpen = false, className, children, ...rest }, ref) => {
    const [open, setOpen] = useState(defaultOpen);

    const classes = ['sds-accordion-item', className]
      .filter(Boolean)
      .join(' ');

    return (
      <div ref={ref} className={classes} {...rest}>
        <button
          type="button"
          className="sds-accordion-header"
          aria-expanded={open}
          onClick={() => setOpen((prev) => !prev)}
        >
          <span className="sds-accordion-header-text">{title}</span>
          <span className="sds-accordion-icon" />
        </button>
        {open && (
          <div className="sds-accordion-panel">
            <div className="sds-accordion-panel-inner">{children}</div>
          </div>
        )}
      </div>
    );
  },
);

AccordionItem.displayName = 'AccordionItem';
