// packages/angular/src/lib/tag.component.ts
import { Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'sds-tag',
  standalone: true,
  imports: [CommonModule],
  host: {
    '[class]': 'hostClasses',
  },
  template: `
    <span *ngIf="dot" class="sds-tag-dot"></span>
    <ng-content />
  `,
})
export class SdsTagComponent {
  @Input() status: 'success' | 'warning' | 'error' | 'info' | 'neutral' | 'purple' | undefined;
  @Input() variant: 'filled' | 'outline' = 'filled';
  @Input() size: 'sm' | 'md' | 'lg' = 'md';
  @Input() dot = false;

  get hostClasses(): string {
    return [
      'sds-tag',
      this.status && `sds-tag--${this.status}`,
      this.variant === 'outline' && 'sds-tag--outline',
      this.size !== 'md' && `sds-tag--${this.size}`,
    ]
      .filter(Boolean)
      .join(' ');
  }
}

// packages/react/src/components/Tag/Tag.tsx
import { forwardRef } from 'react';

export interface TagProps extends React.HTMLAttributes<HTMLSpanElement> {
  status?: 'success' | 'warning' | 'error' | 'info' | 'neutral' | 'purple';
  variant?: 'filled' | 'outline';
  size?: 'sm' | 'md' | 'lg';
  dot?: boolean;
}

export const Tag = forwardRef<HTMLSpanElement, TagProps>(
  (
    {
      status,
      variant = 'filled',
      size = 'md',
      dot,
      className,
      children,
      ...rest
    },
    ref,
  ) => {
    const classes = [
      'sds-tag',
      status && `sds-tag--${status}`,
      variant === 'outline' && 'sds-tag--outline',
      size !== 'md' && `sds-tag--${size}`,
      className,
    ]
      .filter(Boolean)
      .join(' ');

    return (
      <span ref={ref} className={classes} {...rest}>
        {dot && <span className="sds-tag-dot" />}
        {children}
      </span>
    );
  },
);

Tag.displayName = 'Tag';
