// packages/angular/src/lib/select.component.ts
import { Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';

let nextId = 0;

@Component({
  selector: 'sds-select-field',
  standalone: true,
  imports: [CommonModule],
  template: `
    <div class="sds-field">
      <label
        *ngIf="label"
        [attr.for]="selectId"
        [class.sds-field-label]="true"
        [class.sds-field-label--required]="required"
      >
        {{ label }}
      </label>
      <select
        [id]="selectId"
        [class]="selectClasses"
        [required]="required"
      >
        <ng-content />
      </select>
      <p *ngIf="error" class="sds-field-error">{{ error }}</p>
      <p *ngIf="!error && helperText" class="sds-field-helper">{{ helperText }}</p>
    </div>
  `,
})
export class SdsSelectFieldComponent {
  @Input() label = '';
  @Input() helperText = '';
  @Input() error = '';
  @Input() selectSize: 'sm' | 'md' | 'lg' = 'md';
  @Input() required = false;

  selectId = `sds-select-${nextId++}`;

  get selectClasses(): string {
    return [
      'sds-select',
      this.selectSize !== 'md' && `sds-select--${this.selectSize}`,
      this.error && 'sds-select--error',
    ]
      .filter(Boolean)
      .join(' ');
  }
}

// packages/react/src/components/Select/Select.tsx
import { forwardRef, useId } from 'react';

export interface SelectProps
  extends React.SelectHTMLAttributes<HTMLSelectElement> {
  label?: string;
  helperText?: string;
  error?: string;
  selectSize?: 'sm' | 'md' | 'lg';
  required?: boolean;
  children: React.ReactNode;
}

export const Select = forwardRef<HTMLSelectElement, SelectProps>(
  (
    {
      label,
      helperText,
      error,
      selectSize = 'md',
      required,
      className,
      children,
      id: idProp,
      ...rest
    },
    ref,
  ) => {
    const autoId = useId();
    const id = idProp ?? autoId;

    const selectClasses = [
      'sds-select',
      selectSize !== 'md' && `sds-select--${selectSize}`,
      error && 'sds-select--error',
      className,
    ]
      .filter(Boolean)
      .join(' ');

    return (
      <div className="sds-field">
        {label && (
          <label
            htmlFor={id}
            className={[
              'sds-field-label',
              required && 'sds-field-label--required',
            ]
              .filter(Boolean)
              .join(' ')}
          >
            {label}
          </label>
        )}
        <select ref={ref} id={id} className={selectClasses} required={required} {...rest}>
          {children}
        </select>
        {error && <p className="sds-field-error">{error}</p>}
        {!error && helperText && <p className="sds-field-helper">{helperText}</p>}
      </div>
    );
  },
);

Select.displayName = 'Select';
