// packages/angular/src/lib/table.component.ts
import { Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'sds-table-wrapper',
  standalone: true,
  imports: [CommonModule],
  host: {
    class: 'sds-table-container',
  },
  template: `
    <div [class]="tableClasses">
      <ng-content />
    </div>
  `,
})
export class SdsTableWrapperComponent {
  @Input() striped = false;
  @Input() hoverable = false;
  @Input() compact = false;

  get tableClasses(): string {
    return [
      'sds-table',
      this.striped && 'sds-table--striped',
      this.hoverable && 'sds-table--hoverable',
      this.compact && 'sds-table--compact',
    ]
      .filter(Boolean)
      .join(' ');
  }
}

// packages/react/src/components/Table/Table.tsx
import { forwardRef } from 'react';

export interface TableProps
  extends React.TableHTMLAttributes<HTMLTableElement> {
  striped?: boolean;
  hoverable?: boolean;
  compact?: boolean;
}

export const Table = forwardRef<HTMLTableElement, TableProps>(
  ({ striped, hoverable, compact, className, children, ...rest }, ref) => {
    const tableClasses = [
      'sds-table',
      striped && 'sds-table--striped',
      hoverable && 'sds-table--hoverable',
      compact && 'sds-table--compact',
      className,
    ]
      .filter(Boolean)
      .join(' ');

    return (
      <div className="sds-table-container">
        <table ref={ref} className={tableClasses} {...rest}>
          {children}
        </table>
      </div>
    );
  },
);

Table.displayName = 'Table';
