// packages/angular/src/lib/toggle.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'sds-toggle',
  standalone: true,
  imports: [CommonModule],
  template: `
    <label [class]="hostClasses">
      <input
        type="checkbox"
        [checked]="checked"
        [disabled]="disabled"
        (change)="onChange($event)"
        hidden
      />
      <span class="sds-toggle-track">
        <span class="sds-toggle-knob"></span>
      </span>
      {{ label }}
    </label>
  `,
})
export class SdsToggleComponent {
  @Input() label = '';
  @Input() checked = false;
  @Input() disabled = false;
  @Output() checkedChange = new EventEmitter<boolean>();

  get hostClasses(): string {
    return [
      'sds-toggle',
      this.disabled && 'sds-toggle--disabled',
    ]
      .filter(Boolean)
      .join(' ');
  }

  onChange(event: Event): void {
    const target = event.target as HTMLInputElement;
    this.checked = target.checked;
    this.checkedChange.emit(this.checked);
  }
}

// packages/react/src/components/Toggle/Toggle.tsx
import { forwardRef } from 'react';

export interface ToggleProps
  extends Omit<React.InputHTMLAttributes<HTMLInputElement>, 'type'> {
  label?: string;
}

export const Toggle = forwardRef<HTMLInputElement, ToggleProps>(
  ({ label, className, disabled, ...rest }, ref) => {
    const classes = [
      'sds-toggle',
      disabled && 'sds-toggle--disabled',
      className,
    ]
      .filter(Boolean)
      .join(' ');

    return (
      <label className={classes}>
        <input type="checkbox" ref={ref} disabled={disabled} hidden {...rest} />
        <span className="sds-toggle-track">
          <span className="sds-toggle-knob" />
        </span>
        {label}
      </label>
    );
  },
);

Toggle.displayName = 'Toggle';
