// packages/angular/src/lib/segmented-control.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';
import { CommonModule } from '@angular/common';

/* ---------- SegmentedControl ---------- */

@Component({
  selector: 'sds-segmented-control',
  standalone: true,
  imports: [CommonModule],
  host: {
    '[class]': 'hostClasses',
    'role': 'radiogroup',
  },
  template: `<ng-content />`,
})
export class SdsSegmentedControlComponent {
  @Input() size: 'sm' | 'md' | 'lg' = 'md';
  @Input() block = false;
  @Input() value = '';
  @Output() valueChange = new EventEmitter<string>();

  get hostClasses(): string {
    return [
      'sds-segmented',
      this.size === 'sm' && 'sds-segmented--sm',
      this.size === 'lg' && 'sds-segmented--lg',
      this.block && 'sds-segmented--block',
    ]
      .filter(Boolean)
      .join(' ');
  }

  selectOption(optionValue: string): void {
    this.value = optionValue;
    this.valueChange.emit(optionValue);
  }
}

/* ---------- SegmentedOption ---------- */

@Component({
  selector: 'sds-segmented-option',
  standalone: true,
  imports: [CommonModule],
  host: {
    '[class]': 'hostClasses',
    'role': 'radio',
    '[attr.aria-checked]': 'active',
    '(click)': 'onClick()',
  },
  template: `<ng-content />`,
})
export class SdsSegmentedOptionComponent {
  @Input() value = '';
  @Input() active = false;

  get hostClasses(): string {
    return [
      'sds-segmented__option',
      this.active && 'sds-segmented__option--active',
    ]
      .filter(Boolean)
      .join(' ');
  }

  onClick(): void {
    // Parent component handles selection via valueChange
  }
}

// packages/react/src/components/SegmentedControl/SegmentedControl.tsx
import { forwardRef } from 'react';

/* ---------- SegmentedControl ---------- */

export interface SegmentedControlProps
  extends Omit<React.HTMLAttributes<HTMLDivElement>, 'onChange'> {
  size?: 'sm' | 'md' | 'lg';
  block?: boolean;
  value: string;
  onChange: (value: string) => void;
}

export const SegmentedControl = forwardRef<
  HTMLDivElement,
  SegmentedControlProps
>(
  (
    { size = 'md', block, value, onChange, className, children, ...rest },
    ref,
  ) => {
    const classes = [
      'sds-segmented',
      size === 'sm' && 'sds-segmented--sm',
      size === 'lg' && 'sds-segmented--lg',
      block && 'sds-segmented--block',
      className,
    ]
      .filter(Boolean)
      .join(' ');

    return (
      <div ref={ref} className={classes} role="radiogroup" {...rest}>
        {children}
      </div>
    );
  },
);

SegmentedControl.displayName = 'SegmentedControl';

/* ---------- SegmentedOption ---------- */

export interface SegmentedOptionProps
  extends React.ButtonHTMLAttributes<HTMLButtonElement> {
  value: string;
  active?: boolean;
}

export const SegmentedOption = forwardRef<
  HTMLButtonElement,
  SegmentedOptionProps
>(({ value, active, className, children, ...rest }, ref) => {
  const classes = [
    'sds-segmented__option',
    active && 'sds-segmented__option--active',
    className,
  ]
    .filter(Boolean)
    .join(' ');

  return (
    <button
      ref={ref}
      type="button"
      className={classes}
      role="radio"
      aria-checked={active}
      {...rest}
    >
      {children}
    </button>
  );
});

SegmentedOption.displayName = 'SegmentedOption';
