// packages/angular/src/lib/side-navigation.component.ts
import { Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';

/* ---------- SideNavigation ---------- */

@Component({
  selector: 'sds-side-nav',
  standalone: true,
  imports: [CommonModule],
  host: {
    '[class]': 'hostClasses',
  },
  template: `<ng-content />`,
})
export class SdsSideNavComponent {
  @Input() collapsed = false;

  get hostClasses(): string {
    return [
      'sds-sidenav',
      this.collapsed && 'is-collapsed',
    ]
      .filter(Boolean)
      .join(' ');
  }
}

/* ---------- SideNavItem ---------- */

@Component({
  selector: 'sds-side-nav-item',
  standalone: true,
  imports: [CommonModule],
  host: {
    '[class]': 'hostClasses',
  },
  template: `
    <span *ngIf="icon" class="sds-sidenav-icon">
      <ng-content select="[sdsNavIcon]" />
    </span>
    <span class="sds-sidenav-item-label">{{ label }}</span>
    <ng-content />
  `,
})
export class SdsSideNavItemComponent {
  @Input() active = false;
  @Input() icon = false;
  @Input() label = '';

  get hostClasses(): string {
    return [
      'sds-sidenav-item',
      this.active && 'active',
    ]
      .filter(Boolean)
      .join(' ');
  }
}

/* ---------- SideNavGroup ---------- */

@Component({
  selector: 'sds-side-nav-group',
  standalone: true,
  imports: [CommonModule],
  host: {
    class: 'sds-sidenav-group',
  },
  template: `
    <div class="sds-sidenav-group-label">{{ label }}</div>
    <ng-content />
  `,
})
export class SdsSideNavGroupComponent {
  @Input() label = '';
}

// packages/react/src/components/SideNavigation/SideNavigation.tsx
import { forwardRef } from 'react';

/* ---------- SideNavigation ---------- */

export interface SideNavigationProps
  extends React.HTMLAttributes<HTMLElement> {
  collapsed?: boolean;
}

export const SideNavigation = forwardRef<HTMLElement, SideNavigationProps>(
  ({ collapsed, className, children, ...rest }, ref) => {
    const classes = [
      'sds-sidenav',
      collapsed && 'is-collapsed',
      className,
    ]
      .filter(Boolean)
      .join(' ');

    return (
      <nav ref={ref} className={classes} {...rest}>
        {children}
      </nav>
    );
  },
);

SideNavigation.displayName = 'SideNavigation';

/* ---------- SideNavItem ---------- */

export interface SideNavItemProps
  extends React.HTMLAttributes<HTMLDivElement> {
  active?: boolean;
  icon?: React.ReactNode;
  label: string;
}

export const SideNavItem = forwardRef<HTMLDivElement, SideNavItemProps>(
  ({ active, icon, label, className, children, ...rest }, ref) => {
    const classes = [
      'sds-sidenav-item',
      active && 'active',
      className,
    ]
      .filter(Boolean)
      .join(' ');

    return (
      <div ref={ref} className={classes} {...rest}>
        {icon && <span className="sds-sidenav-icon">{icon}</span>}
        <span className="sds-sidenav-item-label">{label}</span>
        {children}
      </div>
    );
  },
);

SideNavItem.displayName = 'SideNavItem';

/* ---------- SideNavGroup ---------- */

export interface SideNavGroupProps
  extends React.HTMLAttributes<HTMLDivElement> {
  label: string;
}

export const SideNavGroup = forwardRef<HTMLDivElement, SideNavGroupProps>(
  ({ label, className, children, ...rest }, ref) => {
    const classes = ['sds-sidenav-group', className]
      .filter(Boolean)
      .join(' ');

    return (
      <div ref={ref} className={classes} {...rest}>
        <div className="sds-sidenav-group-label">{label}</div>
        {children}
      </div>
    );
  },
);

SideNavGroup.displayName = 'SideNavGroup';

/* ---------- SideNavFooter ---------- */

export interface SideNavFooterProps
  extends React.HTMLAttributes<HTMLDivElement> {}

export const SideNavFooter = forwardRef<HTMLDivElement, SideNavFooterProps>(
  ({ className, children, ...rest }, ref) => {
    const classes = ['sds-sidenav-footer', className]
      .filter(Boolean)
      .join(' ');

    return (
      <div ref={ref} className={classes} {...rest}>
        {children}
      </div>
    );
  },
);

SideNavFooter.displayName = 'SideNavFooter';
