// packages/angular/src/lib/stepper.component.ts
import { Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';

/* ---------- Stepper ---------- */

@Component({
  selector: 'sds-stepper',
  standalone: true,
  imports: [CommonModule],
  host: {
    '[class]': 'hostClasses',
  },
  template: `<ng-content />`,
})
export class SdsStepperComponent {
  @Input() direction: 'horizontal' | 'vertical' = 'horizontal';
  @Input() compact = false;

  get hostClasses(): string {
    return [
      'sds-stepper',
      `sds-stepper--${this.direction}`,
      this.compact && 'sds-stepper--compact',
    ]
      .filter(Boolean)
      .join(' ');
  }
}

/* ---------- Step ---------- */

@Component({
  selector: 'sds-step',
  standalone: true,
  imports: [CommonModule],
  host: {
    '[class]': 'hostClasses',
  },
  template: `
    <div class="sds-step__indicator"></div>
    <div class="sds-step__content">
      <div *ngIf="label" class="sds-step__label">{{ label }}</div>
      <div *ngIf="description" class="sds-step__description">{{ description }}</div>
      <ng-content />
    </div>
  `,
})
export class SdsStepComponent {
  @Input() label = '';
  @Input() description = '';
  @Input() status: 'complete' | 'active' | 'pending' = 'pending';

  get hostClasses(): string {
    return [
      'sds-step',
      `sds-step--${this.status}`,
    ].join(' ');
  }
}

// packages/react/src/components/Stepper/Stepper.tsx
import { forwardRef } from 'react';

/* ---------- Stepper ---------- */

export interface StepperProps extends React.HTMLAttributes<HTMLDivElement> {
  direction?: 'horizontal' | 'vertical';
  compact?: boolean;
}

export const Stepper = forwardRef<HTMLDivElement, StepperProps>(
  ({ direction = 'horizontal', compact, className, children, ...rest }, ref) => {
    const classes = [
      'sds-stepper',
      direction === 'vertical' && 'sds-stepper--vertical',
      compact && 'sds-stepper--compact',
      className,
    ]
      .filter(Boolean)
      .join(' ');

    return (
      <div ref={ref} className={classes} {...rest}>
        {children}
      </div>
    );
  },
);

Stepper.displayName = 'Stepper';

/* ---------- Step ---------- */

export interface StepProps extends React.HTMLAttributes<HTMLDivElement> {
  label: string;
  description?: string;
  status?: 'upcoming' | 'active' | 'completed' | 'error';
}

export const Step = forwardRef<HTMLDivElement, StepProps>(
  (
    { label, description, status = 'upcoming', className, children, ...rest },
    ref,
  ) => {
    const classes = [
      'sds-step',
      `sds-step--${status}`,
      className,
    ]
      .filter(Boolean)
      .join(' ');

    return (
      <div ref={ref} className={classes} {...rest}>
        <div className="sds-step__connector" />
        <div className="sds-step__indicator" />
        <div>
          <div className="sds-step__label">{label}</div>
          {description && (
            <div className="sds-step__description">{description}</div>
          )}
        </div>
        {children}
      </div>
    );
  },
);

Step.displayName = 'Step';
