// packages/angular/src/lib/progress.component.ts
import { Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'sds-progress',
  standalone: true,
  imports: [CommonModule],
  host: {
    '[class]': 'hostClasses',
    'role': 'progressbar',
    '[attr.aria-valuenow]': 'indeterminate ? undefined : value',
    '[attr.aria-valuemin]': '0',
    '[attr.aria-valuemax]': '100',
  },
  template: `
    <div *ngIf="label" class="sds-progress__label">
      <span>{{ label }}</span>
      <span *ngIf="!indeterminate">{{ value }}%</span>
    </div>
    <div class="sds-progress__track">
      <div
        class="sds-progress__bar"
        [style.width.%]="indeterminate ? 100 : value"
      ></div>
    </div>
  `,
})
export class SdsProgressComponent {
  @Input() value = 0;
  @Input() size: 'sm' | 'md' | 'lg' = 'md';
  @Input() status: 'default' | 'success' | 'warning' | 'error' = 'default';
  @Input() indeterminate = false;
  @Input() label = '';

  get hostClasses(): string {
    return [
      'sds-progress',
      `sds-progress--${this.size}`,
      this.status !== 'default' && `sds-progress--${this.status}`,
      this.indeterminate && 'sds-progress--indeterminate',
    ]
      .filter(Boolean)
      .join(' ');
  }
}

// packages/react/src/components/Progress/Progress.tsx
import { forwardRef } from 'react';

export interface ProgressProps extends React.HTMLAttributes<HTMLDivElement> {
  value?: number;
  size?: 'sm' | 'md' | 'lg';
  status?: 'default' | 'success' | 'error' | 'warning';
  indeterminate?: boolean;
  label?: string;
}

export const Progress = forwardRef<HTMLDivElement, ProgressProps>(
  (
    {
      value,
      size = 'md',
      status = 'default',
      indeterminate,
      label,
      className,
      ...rest
    },
    ref,
  ) => {
    const classes = [
      'sds-progress',
      size !== 'md' && `sds-progress--${size}`,
      status !== 'default' && `sds-progress--${status}`,
      indeterminate && 'sds-progress--indeterminate',
      className,
    ]
      .filter(Boolean)
      .join(' ');

    const clampedValue =
      value !== undefined ? Math.min(100, Math.max(0, value)) : 0;

    return (
      <div
        ref={ref}
        className={classes}
        role="progressbar"
        aria-valuenow={indeterminate ? undefined : clampedValue}
        aria-valuemin={0}
        aria-valuemax={100}
        {...rest}
      >
        {label && <span className="sds-progress__label">{label}</span>}
        <div className="sds-progress__track">
          <div
            className="sds-progress__fill"
            style={
              indeterminate ? undefined : { width: `${clampedValue}%` }
            }
          />
        </div>
      </div>
    );
  },
);

Progress.displayName = 'Progress';
