// packages/angular/src/lib/checkbox.component.ts
import {
  Component,
  Input,
  Output,
  EventEmitter,
  ViewChild,
  ElementRef,
  AfterViewInit,
  OnChanges,
  SimpleChanges,
} from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'sds-checkbox',
  standalone: true,
  imports: [CommonModule],
  host: {
    '[class]': 'hostClasses',
  },
  template: `
    <label [class]="hostClasses">
      <input
        #inputEl
        type="checkbox"
        [checked]="checked"
        [disabled]="disabled"
        (change)="onChange($event)"
        hidden
      />
      <span class="sds-checkbox-box">
        <span *ngIf="indeterminate" class="sds-checkbox-dash"></span>
        <svg *ngIf="!indeterminate" viewBox="0 0 12 10" fill="none" aria-hidden="true">
          <path
            d="M1 5l3.5 3.5L11 1"
            stroke="currentColor"
            stroke-width="2"
            stroke-linecap="round"
            stroke-linejoin="round"
          />
        </svg>
      </span>
      {{ label }}
    </label>
  `,
})
export class SdsCheckboxComponent implements AfterViewInit, OnChanges {
  @Input() label = '';
  @Input() checked = false;
  @Input() indeterminate = false;
  @Input() disabled = false;
  @Output() checkedChange = new EventEmitter<boolean>();

  @ViewChild('inputEl') inputEl!: ElementRef<HTMLInputElement>;

  get hostClasses(): string {
    return [
      'sds-checkbox',
      this.indeterminate && 'sds-checkbox--indeterminate',
      this.disabled && 'sds-checkbox--disabled',
    ]
      .filter(Boolean)
      .join(' ');
  }

  ngAfterViewInit(): void {
    this.syncIndeterminate();
  }

  ngOnChanges(changes: SimpleChanges): void {
    if (changes['indeterminate'] && this.inputEl) {
      this.syncIndeterminate();
    }
  }

  onChange(event: Event): void {
    const target = event.target as HTMLInputElement;
    this.checked = target.checked;
    this.checkedChange.emit(this.checked);
  }

  private syncIndeterminate(): void {
    if (this.inputEl?.nativeElement) {
      this.inputEl.nativeElement.indeterminate = this.indeterminate;
    }
  }
}

// packages/react/src/components/Checkbox/Checkbox.tsx
import { forwardRef, useEffect, useRef } from 'react';

export interface CheckboxProps
  extends Omit<React.InputHTMLAttributes<HTMLInputElement>, 'type'> {
  label?: string;
  indeterminate?: boolean;
}

export const Checkbox = forwardRef<HTMLInputElement, CheckboxProps>(
  ({ label, indeterminate = false, className, disabled, ...rest }, ref) => {
    const internalRef = useRef<HTMLInputElement | null>(null);

    useEffect(() => {
      if (internalRef.current) {
        internalRef.current.indeterminate = indeterminate;
      }
    }, [indeterminate]);

    const classes = [
      'sds-checkbox',
      indeterminate && 'sds-checkbox--indeterminate',
      disabled && 'sds-checkbox--disabled',
      className,
    ]
      .filter(Boolean)
      .join(' ');

    return (
      <label className={classes}>
        <input
          type="checkbox"
          ref={(node) => {
            internalRef.current = node;
            if (typeof ref === 'function') {
              ref(node);
            } else if (ref) {
              (ref as React.MutableRefObject<HTMLInputElement | null>).current = node;
            }
          }}
          disabled={disabled}
          hidden
          {...rest}
        />
        <span className="sds-checkbox-box">
          {indeterminate ? (
            <span className="sds-checkbox-dash" />
          ) : (
            <svg viewBox="0 0 12 10" fill="none" aria-hidden="true">
              <path
                d="M1 5l3.5 3.5L11 1"
                stroke="currentColor"
                strokeWidth="2"
                strokeLinecap="round"
                strokeLinejoin="round"
              />
            </svg>
          )}
        </span>
        {label}
      </label>
    );
  },
);

Checkbox.displayName = 'Checkbox';
