// packages/angular/src/lib/tabs.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';
import { CommonModule } from '@angular/common';

/* ---------- Tabs ---------- */

@Component({
  selector: 'sds-tabs',
  standalone: true,
  imports: [CommonModule],
  host: {
    '[class]': 'hostClasses',
  },
  template: `<ng-content />`,
})
export class SdsTabsComponent {
  @Input() size: 'sm' | 'md' = 'md';

  get hostClasses(): string {
    return [
      'sds-tabs',
      this.size === 'sm' && 'sds-tabs--sm',
    ]
      .filter(Boolean)
      .join(' ');
  }
}

/* ---------- Tab ---------- */

@Component({
  selector: 'sds-tab',
  standalone: true,
  imports: [CommonModule],
  host: {
    '[class]': 'hostClasses',
    'role': 'tab',
    '[attr.aria-selected]': 'active',
  },
  template: `
    {{ label }}
    <span *ngIf="badge !== undefined" class="sds-tab-badge">{{ badge }}</span>
  `,
})
export class SdsTabComponent {
  @Input() label = '';
  @Input() active = false;
  @Input() badge: string | number | undefined;

  get hostClasses(): string {
    return [
      'sds-tab',
      this.active && 'is-active',
    ]
      .filter(Boolean)
      .join(' ');
  }
}

/* ---------- Tab Panel ---------- */

@Component({
  selector: 'sds-tab-panel',
  standalone: true,
  host: {
    class: 'sds-tab-panel',
    'role': 'tabpanel',
  },
  template: `<ng-content />`,
})
export class SdsTabPanelComponent {}

// packages/react/src/components/Tabs/Tabs.tsx
import { forwardRef } from 'react';

/* ---------- Tabs ---------- */

export interface TabsProps extends React.HTMLAttributes<HTMLDivElement> {
  size?: 'sm' | 'md';
}

export const Tabs = forwardRef<HTMLDivElement, TabsProps>(
  ({ size = 'md', className, children, ...rest }, ref) => {
    const classes = [
      'sds-tabs',
      size === 'sm' && 'sds-tabs--sm',
      className,
    ]
      .filter(Boolean)
      .join(' ');

    return (
      <div ref={ref} className={classes} {...rest}>
        {children}
      </div>
    );
  },
);

Tabs.displayName = 'Tabs';

/* ---------- TabList ---------- */

export interface TabListProps extends React.HTMLAttributes<HTMLDivElement> {}

export const TabList = forwardRef<HTMLDivElement, TabListProps>(
  ({ className, children, ...rest }, ref) => {
    const classes = ['sds-tab-list', className].filter(Boolean).join(' ');

    return (
      <div ref={ref} className={classes} role="tablist" {...rest}>
        {children}
      </div>
    );
  },
);

TabList.displayName = 'TabList';

/* ---------- Tab ---------- */

export interface TabProps
  extends React.ButtonHTMLAttributes<HTMLButtonElement> {
  label: string;
  active?: boolean;
  badge?: React.ReactNode;
}

export const Tab = forwardRef<HTMLButtonElement, TabProps>(
  ({ label, active, badge, className, ...rest }, ref) => {
    const classes = ['sds-tab', active && 'is-active', className]
      .filter(Boolean)
      .join(' ');

    return (
      <button ref={ref} className={classes} role="tab" aria-selected={active} {...rest}>
        {label}
        {badge !== undefined && <span className="sds-tab-badge">{badge}</span>}
      </button>
    );
  },
);

Tab.displayName = 'Tab';

/* ---------- TabPanel ---------- */

export interface TabPanelProps extends React.HTMLAttributes<HTMLDivElement> {}

export const TabPanel = forwardRef<HTMLDivElement, TabPanelProps>(
  ({ className, children, ...rest }, ref) => {
    const classes = ['sds-tab-panel', className].filter(Boolean).join(' ');

    return (
      <div ref={ref} className={classes} role="tabpanel" {...rest}>
        {children}
      </div>
    );
  },
);

TabPanel.displayName = 'TabPanel';
