// packages/angular/src/lib/banner.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'sds-banner',
  standalone: true,
  imports: [CommonModule],
  host: {
    '[class]': 'hostClasses',
    'role': 'alert',
  },
  template: `
    <div class="sds-banner__content">
      <div *ngIf="title" class="sds-banner__title">{{ title }}</div>
      <div *ngIf="message" class="sds-banner__message">{{ message }}</div>
      <ng-content />
    </div>
    <button
      *ngIf="dismissible"
      type="button"
      class="sds-banner__dismiss"
      (click)="dismissed.emit()"
      aria-label="Dismiss"
    >
      &times;
    </button>
  `,
})
export class SdsBannerComponent {
  @Input() variant: 'info' | 'success' | 'warning' | 'error' = 'info';
  @Input() title = '';
  @Input() message = '';
  @Input() dismissible = false;
  @Output() dismissed = new EventEmitter<void>();

  get hostClasses(): string {
    return [
      'sds-banner',
      `sds-banner--${this.variant}`,
    ].join(' ');
  }
}

// packages/react/src/components/Banner/Banner.tsx
import { forwardRef } from 'react';

export interface BannerProps extends React.HTMLAttributes<HTMLDivElement> {
  variant?: 'info' | 'warning' | 'error' | 'success';
  title?: string;
  message?: string;
  icon?: React.ReactNode;
  dismissible?: boolean;
  onDismiss?: () => void;
  actions?: React.ReactNode;
}

export const Banner = forwardRef<HTMLDivElement, BannerProps>(
  (
    {
      variant = 'info',
      title,
      message,
      icon,
      dismissible,
      onDismiss,
      actions,
      className,
      children,
      ...rest
    },
    ref,
  ) => {
    const classes = [
      'sds-banner',
      `sds-banner--${variant}`,
      className,
    ]
      .filter(Boolean)
      .join(' ');

    return (
      <div ref={ref} className={classes} role="alert" {...rest}>
        {icon && <span className="sds-banner__icon">{icon}</span>}
        <div className="sds-banner__content">
          {title && <div className="sds-banner__title">{title}</div>}
          {(message || children) && (
            <div className="sds-banner__message">{message || children}</div>
          )}
        </div>
        {actions && <div className="sds-banner__actions">{actions}</div>}
        {dismissible && (
          <button
            type="button"
            className="sds-banner__dismiss"
            onClick={onDismiss}
            aria-label="Dismiss"
          >
            &times;
          </button>
        )}
      </div>
    );
  },
);

Banner.displayName = 'Banner';
