// packages/angular/src/lib/badge.component.ts
import { Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'sds-badge',
  standalone: true,
  imports: [CommonModule],
  host: {
    '[class]': 'hostClasses',
  },
  template: `{{ displayContent }}<ng-content *ngIf="count === undefined" />`,
})
export class SdsBadgeComponent {
  @Input() variant: 'default' | 'primary' | 'danger' | 'danger-solid' = 'default';
  @Input() size: 'sm' | 'md' | 'lg' = 'md';
  @Input() count: number | undefined;
  @Input() maxCount = 99;

  get hostClasses(): string {
    return [
      'sds-badge',
      `sds-badge--${this.variant}`,
      this.size !== 'md' && `sds-badge--${this.size}`,
    ]
      .filter(Boolean)
      .join(' ');
  }

  get displayContent(): string {
    if (this.count === undefined) return '';
    return this.count > this.maxCount ? `${this.maxCount}+` : String(this.count);
  }
}

// packages/react/src/components/Badge/Badge.tsx
import { forwardRef } from 'react';

export interface BadgeProps extends React.HTMLAttributes<HTMLSpanElement> {
  variant?: 'default' | 'primary' | 'danger' | 'danger-solid';
  size?: 'sm' | 'md' | 'lg';
  count?: number;
  maxCount?: number;
}

export const Badge = forwardRef<HTMLSpanElement, BadgeProps>(
  (
    {
      variant = 'default',
      size = 'md',
      count,
      maxCount = 99,
      className,
      children,
      ...rest
    },
    ref,
  ) => {
    const classes = [
      'sds-badge',
      `sds-badge--${variant}`,
      size !== 'md' && `sds-badge--${size}`,
      className,
    ]
      .filter(Boolean)
      .join(' ');

    const displayContent =
      count !== undefined
        ? count > maxCount
          ? `${maxCount}+`
          : String(count)
        : children;

    return (
      <span ref={ref} className={classes} {...rest}>
        {displayContent}
      </span>
    );
  },
);

Badge.displayName = 'Badge';
