// packages/angular/src/lib/stat-card.component.ts
import { Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'sds-stat-card',
  standalone: true,
  imports: [CommonModule],
  host: {
    '[class]': 'hostClasses',
  },
  template: `
    <div class="sds-stat-card__label">{{ label }}</div>
    <div class="sds-stat-card__value">{{ value }}</div>
    <div
      *ngIf="trendValue"
      [class]="trendClasses"
    >
      <span *ngIf="trendDirection === 'up'" class="sds-stat-card__trend-icon">&#9650;</span>
      <span *ngIf="trendDirection === 'down'" class="sds-stat-card__trend-icon">&#9660;</span>
      {{ trendValue }}
    </div>
    <div *ngIf="footer" class="sds-stat-card__footer">{{ footer }}</div>
    <ng-content />
  `,
})
export class SdsStatCardComponent {
  @Input() label = '';
  @Input() value = '';
  @Input() trendDirection: 'up' | 'down' | undefined;
  @Input() trendValue = '';
  @Input() trendPositive = true;
  @Input() compact = false;
  @Input() highlight = false;
  @Input() footer = '';

  get hostClasses(): string {
    return [
      'sds-stat-card',
      this.compact && 'sds-stat-card--compact',
      this.highlight && 'sds-stat-card--highlight',
    ]
      .filter(Boolean)
      .join(' ');
  }

  get trendClasses(): string {
    return [
      'sds-stat-card__trend',
      this.trendPositive
        ? 'sds-stat-card__trend--positive'
        : 'sds-stat-card__trend--negative',
    ].join(' ');
  }
}

// packages/react/src/components/StatCard/StatCard.tsx
import { forwardRef } from 'react';

export interface StatCardProps extends React.HTMLAttributes<HTMLDivElement> {
  label: string;
  value: string | number;
  trend?: {
    direction: 'up' | 'down' | 'neutral';
    value: string;
    positive?: boolean;
  };
  compact?: boolean;
  highlight?: 'info' | 'critical' | 'health';
  icon?: React.ReactNode;
  footer?: React.ReactNode;
}

export const StatCard = forwardRef<HTMLDivElement, StatCardProps>(
  (
    {
      label,
      value,
      trend,
      compact,
      highlight,
      icon,
      footer,
      className,
      children,
      ...rest
    },
    ref,
  ) => {
    const classes = [
      'sds-stat-card',
      compact && 'sds-stat-card--compact',
      highlight && 'sds-stat-card--highlighted',
      highlight && `sds-stat-card--highlighted-${highlight}`,
      className,
    ]
      .filter(Boolean)
      .join(' ');

    const trendClasses = trend
      ? [
          'sds-stat-card__trend',
          `sds-stat-card__trend--${trend.direction}`,
          trend.positive !== undefined &&
            (trend.positive
              ? 'sds-stat-card__trend--positive'
              : 'sds-stat-card__trend--negative'),
        ]
          .filter(Boolean)
          .join(' ')
      : undefined;

    return (
      <div ref={ref} className={classes} {...rest}>
        {icon && <span className="sds-stat-card__icon">{icon}</span>}
        <span className="sds-stat-card__label">{label}</span>
        <span className="sds-stat-card__value">{value}</span>
        {trend && <span className={trendClasses}>{trend.value}</span>}
        {footer && <div className="sds-stat-card__footer">{footer}</div>}
        {children}
      </div>
    );
  },
);

StatCard.displayName = 'StatCard';
