// packages/react/src/components/Alert/Alert.tsx
import { forwardRef } from 'react';

export interface AlertProps extends React.HTMLAttributes<HTMLDivElement> {
  variant?: 'info' | 'warning' | 'error' | 'success';
  title?: string;
  icon?: React.ReactNode;
  dismissible?: boolean;
  onDismiss?: () => void;
  compact?: boolean;
  actions?: React.ReactNode;
}

export const Alert = forwardRef<HTMLDivElement, AlertProps>(
  (
    {
      variant = 'info',
      title,
      icon,
      dismissible,
      onDismiss,
      compact,
      actions,
      className,
      children,
      ...rest
    },
    ref,
  ) => {
    const classes = [
      'sds-alert',
      `sds-alert--${variant}`,
      compact && 'sds-alert--compact',
      className,
    ]
      .filter(Boolean)
      .join(' ');

    return (
      <div ref={ref} className={classes} role="alert" {...rest}>
        {icon && <span className="sds-alert__icon">{icon}</span>}
        <div className="sds-alert__content">
          {title && <div className="sds-alert__title">{title}</div>}
          {children && <div className="sds-alert__message">{children}</div>}
        </div>
        {actions && <div className="sds-alert__actions">{actions}</div>}
        {dismissible && (
          <button
            type="button"
            className="sds-alert__dismiss"
            onClick={onDismiss}
            aria-label="Dismiss"
          >
            &times;
          </button>
        )}
      </div>
    );
  },
);

Alert.displayName = 'Alert';

// packages/angular/src/lib/alert.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'sds-alert',
  standalone: true,
  imports: [CommonModule],
  host: {
    '[class]': 'hostClasses',
    'role': 'alert',
  },
  template: `
    <ng-content select="[sdsAlertIcon]" />
    <div class="sds-alert__content">
      <div *ngIf="title" class="sds-alert__title">{{ title }}</div>
      <div class="sds-alert__message">
        <ng-content />
      </div>
    </div>
    <ng-content select="[sdsAlertActions]" />
    <button
      *ngIf="dismissible"
      type="button"
      class="sds-alert__dismiss"
      (click)="dismissed.emit()"
      aria-label="Dismiss"
    >
      &times;
    </button>
  `,
})
export class SdsAlertComponent {
  @Input() variant: 'info' | 'warning' | 'error' | 'success' = 'info';
  @Input() title = '';
  @Input() dismissible = false;
  @Input() compact = false;
  @Output() dismissed = new EventEmitter<void>();

  get hostClasses(): string {
    return [
      'sds-alert',
      `sds-alert--${this.variant}`,
      this.compact && 'sds-alert--compact',
    ]
      .filter(Boolean)
      .join(' ');
  }
}
