// packages/react/src/components/Button/Button.tsx
import { forwardRef } from 'react';

export interface ButtonProps
  extends React.ButtonHTMLAttributes<HTMLButtonElement> {
  variant?: 'primary' | 'secondary' | 'tertiary' | 'danger' | 'danger-outline';
  size?: 'sm' | 'md' | 'lg';
  icon?: React.ReactNode;
  iconOnly?: boolean;
}

export const Button = forwardRef<HTMLButtonElement, ButtonProps>(
  (
    {
      variant = 'primary',
      size = 'md',
      icon,
      iconOnly = false,
      className,
      children,
      ...rest
    },
    ref,
  ) => {
    const classes = [
      'sds-btn',
      `sds-btn--${variant}`,
      `sds-btn--${size}`,
      icon && 'sds-btn--icon',
      iconOnly && 'sds-btn--icon-only',
      className,
    ]
      .filter(Boolean)
      .join(' ');

    return (
      <button ref={ref} className={classes} {...rest}>
        {icon}
        {!iconOnly && children}
      </button>
    );
  },
);

Button.displayName = 'Button';

// packages/angular/src/lib/button.component.ts
import { Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'sds-button',
  standalone: true,
  imports: [CommonModule],
  host: {
    '[class]': 'hostClasses',
  },
  template: `
    <ng-content select="[sdsButtonIcon]" />
    <ng-content *ngIf="!iconOnly" />
  `,
})
export class SdsButtonComponent {
  @Input() variant: 'primary' | 'secondary' | 'tertiary' | 'danger' | 'danger-outline' = 'primary';
  @Input() size: 'sm' | 'md' | 'lg' = 'md';
  @Input() icon = false;
  @Input() iconOnly = false;

  get hostClasses(): string {
    return [
      'sds-btn',
      `sds-btn--${this.variant}`,
      `sds-btn--${this.size}`,
      this.icon && 'sds-btn--icon',
      this.iconOnly && 'sds-btn--icon-only',
    ]
      .filter(Boolean)
      .join(' ');
  }
}
