// packages/react/src/components/Input/Input.tsx
import { forwardRef, useId } from 'react';

export interface InputProps
  extends React.InputHTMLAttributes<HTMLInputElement> {
  label?: string;
  helperText?: string;
  error?: string;
  success?: string;
  inputSize?: 'sm' | 'md' | 'lg';
  leadingIcon?: React.ReactNode;
  trailingIcon?: React.ReactNode;
  required?: boolean;
}

export const Input = forwardRef<HTMLInputElement, InputProps>(
  (
    {
      label,
      helperText,
      error,
      success,
      inputSize = 'md',
      leadingIcon,
      trailingIcon,
      required,
      className,
      id: idProp,
      ...rest
    },
    ref,
  ) => {
    const autoId = useId();
    const id = idProp ?? autoId;

    const inputClasses = [
      'sds-input',
      inputSize !== 'md' && `sds-input--${inputSize}`,
      error && 'sds-input--error',
      success && !error && 'sds-input--success',
      leadingIcon && 'sds-input--has-leading-icon',
      trailingIcon && 'sds-input--has-trailing-icon',
      className,
    ]
      .filter(Boolean)
      .join(' ');

    return (
      <div className="sds-field">
        {label && (
          <label
            htmlFor={id}
            className={[
              'sds-field-label',
              required && 'sds-field-label--required',
            ]
              .filter(Boolean)
              .join(' ')}
          >
            {label}
          </label>
        )}
        <div className="sds-input-wrapper">
          {leadingIcon && (
            <span className="sds-input-icon--leading">{leadingIcon}</span>
          )}
          <input ref={ref} id={id} className={inputClasses} required={required} {...rest} />
          {trailingIcon && (
            <span className="sds-input-icon--trailing">{trailingIcon}</span>
          )}
        </div>
        {error && <p className="sds-field-error">{error}</p>}
        {!error && success && <p className="sds-field-success">{success}</p>}
        {!error && !success && helperText && (
          <p className="sds-field-helper">{helperText}</p>
        )}
      </div>
    );
  },
);

Input.displayName = 'Input';

// packages/angular/src/lib/input.component.ts
import { Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';

let nextId = 0;

@Component({
  selector: 'sds-input-field',
  standalone: true,
  imports: [CommonModule],
  template: `
    <div class="sds-field">
      <label
        *ngIf="label"
        [attr.for]="inputId"
        [class.sds-field-label]="true"
        [class.sds-field-label--required]="required"
      >
        {{ label }}
      </label>
      <div class="sds-input-wrapper">
        <input
          [id]="inputId"
          [class]="inputClasses"
          [required]="required"
        />
      </div>
      <p *ngIf="error" class="sds-field-error">{{ error }}</p>
      <p *ngIf="!error && success" class="sds-field-success">{{ success }}</p>
      <p *ngIf="!error && !success && helperText" class="sds-field-helper">{{ helperText }}</p>
    </div>
  `,
})
export class SdsInputFieldComponent {
  @Input() label = '';
  @Input() helperText = '';
  @Input() error = '';
  @Input() success = '';
  @Input() inputSize: 'sm' | 'md' | 'lg' = 'md';
  @Input() required = false;

  inputId = `sds-input-${nextId++}`;

  get inputClasses(): string {
    return [
      'sds-input',
      this.inputSize !== 'md' && `sds-input--${this.inputSize}`,
      this.error && 'sds-input--error',
      this.success && !this.error && 'sds-input--success',
    ]
      .filter(Boolean)
      .join(' ');
  }
}
