// packages/react/src/components/Popover/Popover.tsx
import { forwardRef } from 'react';

/* ---------- Popover ---------- */

export interface PopoverProps extends React.HTMLAttributes<HTMLDivElement> {
  open?: boolean;
  onClose?: () => void;
  position?: 'top' | 'bottom' | 'left' | 'right';
  title?: string;
}

export const Popover = forwardRef<HTMLDivElement, PopoverProps>(
  (
    { open, onClose, position = 'bottom', title, className, children, ...rest },
    ref,
  ) => {
    const anchorClasses = ['sds-popover-anchor', className]
      .filter(Boolean)
      .join(' ');

    const popoverClasses = [
      'sds-popover',
      open && 'is-open',
      `sds-popover--${position}`,
    ]
      .filter(Boolean)
      .join(' ');

    return (
      <div ref={ref} className={anchorClasses} {...rest}>
        <div className={popoverClasses}>
          {(title || onClose) && (
            <div className="sds-popover__header">
              {title && <div className="sds-popover__title">{title}</div>}
              {onClose && (
                <button
                  type="button"
                  className="sds-popover__close"
                  onClick={onClose}
                  aria-label="Close"
                >
                  &times;
                </button>
              )}
            </div>
          )}
          {children}
        </div>
      </div>
    );
  },
);

Popover.displayName = 'Popover';

/* ---------- PopoverBody ---------- */

export interface PopoverBodyProps extends React.HTMLAttributes<HTMLDivElement> {}

export const PopoverBody = forwardRef<HTMLDivElement, PopoverBodyProps>(
  ({ className, children, ...rest }, ref) => {
    const classes = ['sds-popover__body', className]
      .filter(Boolean)
      .join(' ');

    return (
      <div ref={ref} className={classes} {...rest}>
        {children}
      </div>
    );
  },
);

PopoverBody.displayName = 'PopoverBody';

/* ---------- PopoverActions ---------- */

export interface PopoverActionsProps
  extends React.HTMLAttributes<HTMLDivElement> {}

export const PopoverActions = forwardRef<HTMLDivElement, PopoverActionsProps>(
  ({ className, children, ...rest }, ref) => {
    const classes = ['sds-popover__actions', className]
      .filter(Boolean)
      .join(' ');

    return (
      <div ref={ref} className={classes} {...rest}>
        {children}
      </div>
    );
  },
);

PopoverActions.displayName = 'PopoverActions';

// packages/angular/src/lib/popover.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'sds-popover-wrapper',
  standalone: true,
  imports: [CommonModule],
  host: {
    '[class]': 'hostClasses',
  },
  template: `
    <ng-content />
    <div *ngIf="open" class="sds-popover" role="dialog">
      <div *ngIf="title" class="sds-popover__header">
        <div class="sds-popover__title">{{ title }}</div>
        <button
          type="button"
          class="sds-popover__close"
          (click)="closed.emit()"
          aria-label="Close"
        >
          &times;
        </button>
      </div>
      <div class="sds-popover__body">
        <ng-content select="[sdsPopoverBody]" />
      </div>
    </div>
  `,
})
export class SdsPopoverWrapperComponent {
  @Input() open = false;
  @Input() position: 'top' | 'bottom' | 'left' | 'right' = 'bottom';
  @Input() title = '';
  @Output() closed = new EventEmitter<void>();

  get hostClasses(): string {
    return [
      'sds-popover-wrapper',
      `sds-popover-wrapper--${this.position}`,
    ].join(' ');
  }
}
