// packages/react/src/components/StatusIndicator/StatusIndicator.tsx
import { forwardRef } from 'react';

export interface StatusIndicatorProps
  extends React.HTMLAttributes<HTMLSpanElement> {
  status?:
    | 'online'
    | 'connected'
    | 'offline'
    | 'disconnected'
    | 'warning'
    | 'degraded'
    | 'error'
    | 'critical'
    | 'scanning'
    | 'syncing';
  size?: 'sm' | 'md' | 'lg';
  label?: string;
}

export const StatusIndicator = forwardRef<HTMLSpanElement, StatusIndicatorProps>(
  ({ status = 'online', size = 'md', label, className, ...rest }, ref) => {
    const classes = [
      'sds-status',
      `sds-status--${status}`,
      size !== 'md' && `sds-status--${size}`,
      className,
    ]
      .filter(Boolean)
      .join(' ');

    return (
      <span ref={ref} className={classes} {...rest}>
        <span className="sds-status__dot" />
        {label && <span className="sds-status__label">{label}</span>}
      </span>
    );
  },
);

StatusIndicator.displayName = 'StatusIndicator';

// packages/angular/src/lib/status-indicator.component.ts
import { Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'sds-status-indicator',
  standalone: true,
  imports: [CommonModule],
  host: {
    '[class]': 'hostClasses',
  },
  template: `
    <span class="sds-status__dot"></span>
    <span *ngIf="label" class="sds-status__label">{{ label }}</span>
  `,
})
export class SdsStatusIndicatorComponent {
  @Input() status:
    | 'online'
    | 'connected'
    | 'offline'
    | 'disconnected'
    | 'warning'
    | 'degraded'
    | 'error'
    | 'critical'
    | 'scanning'
    | 'syncing' = 'online';
  @Input() size: 'sm' | 'md' | 'lg' = 'md';
  @Input() label = '';

  get hostClasses(): string {
    return [
      'sds-status',
      `sds-status--${this.status}`,
      this.size !== 'md' && `sds-status--${this.size}`,
    ]
      .filter(Boolean)
      .join(' ');
  }
}
