// packages/react/src/components/Tooltip/Tooltip.tsx
import { forwardRef } from 'react';

export interface TooltipProps extends React.HTMLAttributes<HTMLDivElement> {
  content: string;
  title?: string;
  position?: 'top' | 'bottom' | 'left' | 'right';
}

export const Tooltip = forwardRef<HTMLDivElement, TooltipProps>(
  (
    { content, title, position = 'top', className, children, ...rest },
    ref,
  ) => {
    const classes = [
      'sds-tooltip',
      `sds-tooltip--${position}`,
      className,
    ]
      .filter(Boolean)
      .join(' ');

    return (
      <div ref={ref} className={classes} {...rest}>
        {children}
        <div role="tooltip">
          {title && <div className="sds-tooltip__title">{title}</div>}
          <div className="sds-tooltip__desc">{content}</div>
        </div>
      </div>
    );
  },
);

Tooltip.displayName = 'Tooltip';

// packages/angular/src/lib/tooltip.component.ts
import { Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'sds-tooltip-wrapper',
  standalone: true,
  imports: [CommonModule],
  host: {
    '[class]': 'hostClasses',
  },
  template: `
    <ng-content />
    <div class="sds-tooltip" role="tooltip">
      <div *ngIf="title" class="sds-tooltip__title">{{ title }}</div>
      <div class="sds-tooltip__content">{{ content }}</div>
    </div>
  `,
})
export class SdsTooltipWrapperComponent {
  @Input() content = '';
  @Input() title = '';
  @Input() position: 'top' | 'bottom' | 'left' | 'right' = 'top';

  get hostClasses(): string {
    return [
      'sds-tooltip-wrapper',
      `sds-tooltip-wrapper--${this.position}`,
    ].join(' ');
  }
}
