// packages/angular/src/lib/tree-view.component.ts
import { Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';

/* ---------- Tree View ---------- */

@Component({
  selector: 'sds-tree-view',
  standalone: true,
  imports: [CommonModule],
  host: {
    class: 'sds-tree-view',
    'role': 'tree',
  },
  template: `<ng-content />`,
})
export class SdsTreeViewComponent {}

/* ---------- Tree Item ---------- */

@Component({
  selector: 'sds-tree-item',
  standalone: true,
  imports: [CommonModule],
  host: {
    '[class]': 'hostClasses',
    'role': 'treeitem',
    '[attr.aria-expanded]': 'hasChildren ? expanded : null',
    '[attr.aria-selected]': 'selected',
    '[attr.aria-disabled]': 'disabled',
  },
  template: `
    <div class="sds-tree-item__row" (click)="toggle()">
      <span
        *ngIf="hasChildren"
        class="sds-tree-item__expand"
        [class.sds-tree-item__expand--open]="expanded"
      >
        &#9656;
      </span>
      <span *ngIf="icon" class="sds-tree-item__icon">{{ icon }}</span>
      <span class="sds-tree-item__label">{{ label }}</span>
    </div>
    <div *ngIf="expanded" class="sds-tree-item__children" role="group">
      <ng-content />
    </div>
  `,
})
export class SdsTreeItemComponent {
  @Input() label = '';
  @Input() icon = '';
  @Input() selected = false;
  @Input() disabled = false;
  @Input() expanded = false;

  get hasChildren(): boolean {
    return true; // Overridden by content projection presence in real usage
  }

  get hostClasses(): string {
    return [
      'sds-tree-item',
      this.selected && 'sds-tree-item--selected',
      this.disabled && 'sds-tree-item--disabled',
    ]
      .filter(Boolean)
      .join(' ');
  }

  toggle(): void {
    if (!this.disabled) {
      this.expanded = !this.expanded;
    }
  }
}

// packages/react/src/components/TreeView/TreeView.tsx
import { forwardRef, useState } from 'react';

/* ---------- TreeView ---------- */

export interface TreeViewProps extends React.HTMLAttributes<HTMLDivElement> {}

export const TreeView = forwardRef<HTMLDivElement, TreeViewProps>(
  ({ className, children, ...rest }, ref) => {
    const classes = ['sds-tree', className].filter(Boolean).join(' ');

    return (
      <div ref={ref} className={classes} role="tree" {...rest}>
        {children}
      </div>
    );
  },
);

TreeView.displayName = 'TreeView';

/* ---------- TreeItem ---------- */

export interface TreeItemProps extends React.HTMLAttributes<HTMLDivElement> {
  label: string;
  icon?: React.ReactNode;
  selected?: boolean;
  disabled?: boolean;
  defaultExpanded?: boolean;
}

export const TreeItem = forwardRef<HTMLDivElement, TreeItemProps>(
  (
    {
      label,
      icon,
      selected,
      disabled,
      defaultExpanded = false,
      className,
      children,
      ...rest
    },
    ref,
  ) => {
    const [expanded, setExpanded] = useState(defaultExpanded);
    const hasChildren = !!children;

    const classes = [
      'sds-tree-item',
      selected && 'sds-tree-item--selected',
      disabled && 'sds-tree-item--disabled',
      className,
    ]
      .filter(Boolean)
      .join(' ');

    return (
      <div ref={ref} className={classes} role="treeitem" {...rest}>
        <div className="sds-tree-item__row">
          <button
            type="button"
            className={[
              'sds-tree-item__toggle',
              !hasChildren && 'sds-tree-item__toggle--hidden',
            ]
              .filter(Boolean)
              .join(' ')}
            onClick={() => setExpanded((prev) => !prev)}
            aria-expanded={hasChildren ? expanded : undefined}
            tabIndex={hasChildren ? 0 : -1}
          >
            {hasChildren ? (expanded ? '▾' : '▸') : null}
          </button>
          {icon && <span className="sds-tree-item__icon">{icon}</span>}
          <span className="sds-tree-item__label">{label}</span>
        </div>
        {hasChildren && expanded && (
          <div role="group">{children}</div>
        )}
      </div>
    );
  },
);

TreeItem.displayName = 'TreeItem';
